---
github_token: "{{ lookup('env', 'GITHUB_TOKEN') | default('', true) }}"
github_repo: "{{ lookup('env', 'GITHUB_REPO') | default('leogallego/summit-netbox-circuits-demo', true) }}"
github_pages_branch: gh-pages
